### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by Cougar**
Hi,

This patch adds necessary files to manage docker containers by Ansible. toolbox needs to be started by bindmounting docker dæmon socket  like this:

```
toolbox --bind=/var/run/docker.sock:/var/run/docker.sock
```

### CODE REVIEW

**Comment by iby** [comment]
Thanks for looking after! CircleCI build failed due to hidden environment variables in pull requests. I moved the necessary ones into configuration, but it failed with a different error. Can you please rebase your work onto master and make sure tests pass and container builds?

**Comment by Cougar** [comment]
About CI test I don't understand why it fails. It still shows that GITHUB_TOKEN variable is missing:

`./build/ci/script/build.sh: line 10: GITHUB_TOKEN: unbound variable`

One more finding. When python path is set to /opt/bin/python, it is such only in CoreOS shell and not in toolbox. At least in my case it is also necessary to have /opt/bin/python inside playbook and this should point to the real python not a wrapper any more. I have two more lines at the end of install script:

``` sh
toolbox mkdir -p /opt/bin
toolbox ln -sf /usr/bin/python /opt/bin
```

 I don't know if it is my setup or how does it work for you? I would send pull request if needed but first I'd like to know how does it work for others without such setup. I also made a simple playbook for that including such script: https://github.com/Cougar/ansible-role-coreos_ansible_install

Here is what happens if this link is missing:

``` sh
>ansible coreos-01 -m setup
coreos-01 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to 85.253.5.126 closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1479200435.3-73540967770272/setup.py\", line 130, in <module>\r\n    exitcode = invoke_module(module, zipped_mod, ANSIBALLZ_PARAMS)\r\n  File \"/home/core/.ansible/tmp/ansible-tmp-1479200435.3-73540967770272/setup.py\", line 37, in invoke_module\r\n    p = subprocess.Popen(['/opt/bin/python', module], env=os.environ, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 711, in __init__\r\n    errread, errwrite)\r\n  File \"/usr/lib/python2.7/subprocess.py\", line 1343, in _execute_child\r\n    raise child_exception\r\nOSError: [Errno 2] No such file or directory\r\n", 
    "msg": "MODULE FAILURE"
}
```

**Comment by iby** [comment]
CI fails because your [circle.yml](https://github.com/version6net/docker-coreos-ansible-toolbox/blob/b2778ac290e09756deb1f999d05ed11249385dea/circle.yml) still appears not updated, make sure to rebase your commits onto latest master – it should look like [this](https://github.com/ianbytchek/docker-coreos-ansible-toolbox/blob/c10513411ffc80d75db4705e7132bd4ff8cc01ad/circle.yml).

I'm not sure I'm following, but it seems as `bootstrap.sh` does what described in [running](https://github.com/ianbytchek/docker-coreos-ansible-toolbox#running) section? In other words, does it try to setup Ansible toolbox on CoreOS with Ansible toolbox before it's available there? :confused:

**Comment by Cougar** [comment]
I rebased my changes. Did you disable CI or it just doesn't show any status?

**Comment by iby** [comment]
Hey! No, it doesn't look like, when they are rebased [your](https://github.com/version6net/docker-coreos-ansible-toolbox/blob/master/circle.yml) circle.yml will look like [mine](https://github.com/ianbytchek/docker-coreos-ansible-toolbox/blob/master/circle.yml). It still doesn't include `GITHUB_TOKEN`. Make sure to push everything to remote once rebased, will probably need to do use `--force`.

**Comment by Cougar** [comment]
It was [here](https://github.com/version6net/docker-coreos-ansible-toolbox/blob/docker/circle.yml) in "docker" branch. This is strange why I couldn't rebase it on top of upstream/master when my own master was some commits behind. Now everything should in in sync.

This is what I did:

```sh
void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git remote -v
origin  git@github.com:version6net/docker-coreos-ansible-toolbox.git (fetch)
origin  git@github.com:version6net/docker-coreos-ansible-toolbox.git (push)
upstream        https://github.com/ianbytchek/docker-coreos-ansible-toolbox (fetch)
upstream        https://github.com/ianbytchek/docker-coreos-ansible-toolbox (push)

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git fetch --all 

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git rebase upstream/master 
Current branch docker is up to date.

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git push origin docker 
Everything up-to-date
```

Then I rebased master first and this made it:

```sh
void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[master]>git rebase upstream/master 
First, rewinding head to replay your work on top of it...
Applying: Use pre-built python modules and update

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[master]>git push -f origin master 
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 268 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To git@github.com:version6net/docker-coreos-ansible-toolbox.git
 + 4f17cf8...251c6e1 master -> master (forced update)

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[master]>git checkout docker 
Switched to branch 'docker'
Your branch is up-to-date with 'origin/docker'.

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git rebase master 
First, rewinding head to replay your work on top of it...
Applying: Add docker and docker-py
Applying: Add bind-mount for /var/run/docker.sock

void:pts38:(12):~/git/docker-coreos-ansible-toolbox[docker]>git push -f origin docker 
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 425 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local objects.
To git@github.com:version6net/docker-coreos-ansible-toolbox.git
 + eca71fc...c4b89de docker -> docker (forced update)
```

Was there anything wrong with my first workflow?

**Pull request closed without merging**
